### ISSUE TITLE
接口错误

### ISSUE THREAD

**Issue by LXH112711** [silie666/jrtt_luck_draw#2]
![屏幕截图 2022-02-17 143942](https://user-images.githubusercontent.com/98231341/154419759-b576e652-c251-439b-90ea-423478739fda.png)
这个报错是怎么回事？

**Comment by silie666** [comment]
> ![屏幕截图 2022-02-17 143942](https://user-images.githubusercontent.com/98231341/154419759-b576e652-c251-439b-90ea-423478739fda.png) 这个报错是怎么回事？

今日头条的报错，提示已经点赞过了再次访问接口报错，问题不大
