### ISSUE TITLE
参数

### ISSUE THREAD

**Issue by LXH112711** [silie666/jrtt_luck_draw#4]
请问“CSRF_SESSION_ID”这个参数哪里找呢

**Comment by silie666** [comment]
> 请问“CSRF_SESSION_ID”这个参数哪里找呢

可以转发一条动态，cookie才会生成

**Comment by LXH112711** [comment]
> > 请问“CSRF_SESSION_ID”这个参数哪里找呢
> 
> 可以转发一条动态，cookie才会生成，可能头条对这个参数用js加密了一下

感谢回复，"X-SECSDK-CSRF-TOKEN"又应该怎么获取呢

**Comment by silie666** [comment]
> > 请问“CSRF_SESSION_ID”这个参数哪里找呢
> 
> 可以转发一条动态或者点赞，cookie才会生成，可能头条对这个参数用js加密了一下

**Comment by silie666** [comment]
> X-SECSDK-CSRF-TOKEN

在请求头里面可以找到

**Comment by silie666** [comment]
> > > 请问“CSRF_SESSION_ID”这个参数哪里找呢
> > 
> > 
> > 可以转发一条动态，cookie才会生成，可能头条对这个参数用js加密了一下
> 
> 感谢回复，"X-SECSDK-CSRF-TOKEN"又应该怎么获取呢

在请求头里面可以找到

**Comment by LXH112711** [comment]
> > > > 请问“CSRF_SESSION_ID”这个参数哪里找呢
> > > 
> > > 
> > > 可以转发一条动态，cookie才会生成，可能头条对这个参数用js加密了一下
> > 
> > 
> > 感谢回复，"X-SECSDK-CSRF-TOKEN"又应该怎么获取呢
> 
> 在请求头里面可以找到

![image](https://user-images.githubusercontent.com/98231341/159638004-35d0f093-b5bc-4ddd-9646-e3fb5cab167a.png)
抱歉又来打扰了，我把参数都填玩后远行直接这样报错了，请问大佬知道是什么原因吗？

**Comment by silie666** [comment]
> > > > > 请问“CSRF_SESSION_ID”这个参数哪里找呢
> > > > 
> > > > 
> > > > 可以转发一条动态，cookie才会生成，可能头条对这个参数用js加密了一下
> > > 
> > > 
> > > 感谢回复，"X-SECSDK-CSRF-TOKEN"又应该怎么获取呢
> > 
> > 
> > 在请求头里面可以找到
> 
> ![image](https://user-images.githubusercontent.com/98231341/159638004-35d0f093-b5bc-4ddd-9646-e3fb5cab167a.png) 抱歉又来打扰了，我把参数都填玩后远行直接这样报错了，请问大佬知道是什么原因吗？

这个我昨天晚上修复了，但不知道为什么github没有把修复代码同步到文件上，现在重新拉下代码

**Comment by LXH112711** [comment]
> > > > > > 请问“CSRF_SESSION_ID”这个参数哪里找呢
> > > > > 
> > > > > 
> > > > > 可以转发一条动态，cookie才会生成，可能头条对这个参数用js加密了一下
> > > > 
> > > > 
> > > > 感谢回复，"X-SECSDK-CSRF-TOKEN"又应该怎么获取呢
> > > 
> > > 
> > > 在请求头里面可以找到
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/98231341/159638004-35d0f093-b5bc-4ddd-9646-e3fb5cab167a.png) 抱歉又来打扰了，我把参数都填玩后远行直接这样报错了，请问大佬知道是什么原因吗？
> 
> 这个我昨天晚上修复了，但不知道为什么github没有把修复代码同步到文件上，现在重新拉下代码

可以运行了，万分感谢
