### ISSUE TITLE
不知道如何添加db.go数据库配置

### ISSUE THREAD

**Issue by AAJk254** [silie666/jrtt_luck_draw#5]
请问如何获取相关的数据文件，参数怎么添加？这个数据库可以不添加吗？。没太理解。非常感谢。

**Comment by silie666** [comment]
> 关的数据文件，参数怎么添加？这个数据库可以不添加吗？。没太理解。非


> 请问如何获取相关的数据文件，参数怎么添加？这个数据库可以不添加吗？。没太理解。非常感谢。

这个只是我学习go的一个小项目，如果不用数据库的话，只要自己手动加多一个个人头条列表接口做判断就可以了，只是我个人喜欢把数据放到数据库里

**Comment by AAJk254** [comment]
那大大请问有考虑过开放一个公共的数据库的接口吗？

**Comment by AAJk254** [comment]
主要是emmm，这玩意儿俺不会搞。有点兴趣想试试看。不懂怎么添加个人头条列表接口，因为我不是程序员，所以有点无赖，如果可以大大方便指导一下吗？

**Comment by silie666** [comment]
> 要是emmm，这玩意儿俺不会搞。有点兴趣想试试看。不懂怎么添加个人头条列表接口，因为我不是程序员，所以有点无赖，如果可以大大方便指导一下

其实想要完善这个项目的话，可以做到只填账号自动登录自动爬取的效果，就跟我另一个小脚本ffxiv自动签到一样自动登录，但头条能中的都是小礼品就没多研究，如果以后有空就完善下吧。

**Comment by AAJk254** [comment]
哎嘿，感谢大佬。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月14日(周四) 下午2:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [silie666/jrtt_luck_draw] 不知道如何添加db.go数据库配置 (Issue #5)




  
要是emmm，这玩意儿俺不会搞。有点兴趣想试试看。不懂怎么添加个人头条列表接口，因为我不是程序员，所以有点无赖，如果可以大大方便指导一下
  
其实想要完善这个项目的话，可以做到只填账号自动登录自动爬取的效果，就跟我另一个小脚本ffxiv自动签到一样自动登录，但头条能中的都是小礼品就没多研究，如果以后有空就完善下吧。

**Comment by Be-boy** [comment]
作者大大我运行日志显示都是  不满足条件  怎么回事啊，我的账号数据都填了啊
